default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default
  database: music_prod_development

test:
  <<: *default
  database: music_prod_test

production:
  <<: *default
  database: music_prod_production
  username: music_prod
  password: <%= ENV["MY_API_APP_DATABASE_PASSWORD"] %>
